allowBuilds:
  esbuild: true
  usocket: set this to true or false
catalog:
  vite-plus: 0.2.9
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
